// This file was generated by liblab | https://liblab.com/

using PostmanClient;
using PostmanClient.Config;
using Environment = PostmanClient.Http.Environment;

var apiKeyConfig = new ApiKeyAuthConfig("YOUR_API_KEY");

var config = new PostmanClientConfig
{
    Environment = Environment.Default,
    ApiKeyAuth = apiKeyConfig
};

var client = new PostmanClientClient(config);

var response = await client.Billing.GetAccountsAsync();

Console.WriteLine(response);
