// This file was generated by liblab | https://liblab.com/

using System.Net.Http.Json;
using PostmanClient.Http;
using PostmanClient.Http.Exceptions;
using PostmanClient.Http.Extensions;
using PostmanClient.Http.Serialization;
using PostmanClient.Models;

namespace PostmanClient.Services;

public class CollectionFoldersService : BaseService
{
    internal CollectionFoldersService(HttpClient httpClient)
        : base(httpClient) { }

    /// <summary>Gets all comments left by users in a folder.</summary>
    /// <param name="collectionId">The collection's unique ID.</param>
    /// <param name="folderId">The folder's unique ID.</param>
    public async Task<CommentResponse> GetFolderCommentsAsync(
        string collectionId,
        string folderId,
        CancellationToken cancellationToken = default
    )
    {
        ArgumentNullException.ThrowIfNull(collectionId, nameof(collectionId));
        ArgumentNullException.ThrowIfNull(folderId, nameof(folderId));

        var request = new RequestBuilder(
            HttpMethod.Get,
            "collections/{collectionId}/folders/{folderId}/comments"
        )
            .SetPathParameter("collectionId", collectionId)
            .SetPathParameter("folderId", folderId)
            .Build();

        var response = await _httpClient
            .SendAsync(request, cancellationToken)
            .ConfigureAwait(false);

        return await response
                .EnsureSuccessfulResponse()
                .Content.ReadFromJsonAsync<CommentResponse>(
                    _jsonSerializerOptions,
                    cancellationToken
                )
                .ConfigureAwait(false) ?? throw new Exception("Failed to deserialize response.");
    }

    /// <summary>
    /// Creates a comment on a folder.
    ///
    /// **Note:**
    ///
    /// This endpoint accepts a max of 10,000 characters.
    /// </summary>
    /// <param name="collectionId">The collection's unique ID.</param>
    /// <param name="folderId">The folder's unique ID.</param>
    public async Task<CommentCreatedUpdated> CreateFolderCommentAsync(
        CommentCreateUpdate input,
        string collectionId,
        string folderId,
        CancellationToken cancellationToken = default
    )
    {
        ArgumentNullException.ThrowIfNull(input, nameof(input));
        ArgumentNullException.ThrowIfNull(collectionId, nameof(collectionId));
        ArgumentNullException.ThrowIfNull(folderId, nameof(folderId));

        var request = new RequestBuilder(
            HttpMethod.Post,
            "collections/{collectionId}/folders/{folderId}/comments"
        )
            .SetPathParameter("collectionId", collectionId)
            .SetPathParameter("folderId", folderId)
            .SetContentAsJson(input, _jsonSerializerOptions)
            .Build();

        var response = await _httpClient
            .SendAsync(request, cancellationToken)
            .ConfigureAwait(false);

        return await response
                .EnsureSuccessfulResponse()
                .Content.ReadFromJsonAsync<CommentCreatedUpdated>(
                    _jsonSerializerOptions,
                    cancellationToken
                )
                .ConfigureAwait(false) ?? throw new Exception("Failed to deserialize response.");
    }

    /// <summary>
    /// Updates a comment on a folder.
    ///
    /// **Note:**
    ///
    /// This endpoint accepts a max of 10,000 characters.
    /// </summary>
    /// <param name="collectionId">The collection's unique ID.</param>
    /// <param name="folderId">The folder's unique ID.</param>
    /// <param name="commentId">The comment's ID.</param>
    public async Task<CommentCreatedUpdated> UpdateFolderCommentAsync(
        CommentCreateUpdate input,
        string collectionId,
        string folderId,
        long commentId,
        CancellationToken cancellationToken = default
    )
    {
        ArgumentNullException.ThrowIfNull(input, nameof(input));
        ArgumentNullException.ThrowIfNull(collectionId, nameof(collectionId));
        ArgumentNullException.ThrowIfNull(folderId, nameof(folderId));

        var request = new RequestBuilder(
            HttpMethod.Put,
            "collections/{collectionId}/folders/{folderId}/comments/{commentId}"
        )
            .SetPathParameter("collectionId", collectionId)
            .SetPathParameter("folderId", folderId)
            .SetPathParameter("commentId", commentId)
            .SetContentAsJson(input, _jsonSerializerOptions)
            .Build();

        var response = await _httpClient
            .SendAsync(request, cancellationToken)
            .ConfigureAwait(false);

        return await response
                .EnsureSuccessfulResponse()
                .Content.ReadFromJsonAsync<CommentCreatedUpdated>(
                    _jsonSerializerOptions,
                    cancellationToken
                )
                .ConfigureAwait(false) ?? throw new Exception("Failed to deserialize response.");
    }

    /// <summary>
    /// Deletes a comment from a folder. On success, this returns an HTTP `204 No Content` response
    ///
    /// **Note:**
    ///
    /// Deleting the first comment of a thread deletes all the comments in the thread.
    /// </summary>
    /// <param name="collectionId">The collection's unique ID.</param>
    /// <param name="folderId">The folder's unique ID.</param>
    /// <param name="commentId">The comment's ID.</param>
    public async Task DeleteFolderCommentAsync(
        string collectionId,
        string folderId,
        long commentId,
        CancellationToken cancellationToken = default
    )
    {
        ArgumentNullException.ThrowIfNull(collectionId, nameof(collectionId));
        ArgumentNullException.ThrowIfNull(folderId, nameof(folderId));

        var request = new RequestBuilder(
            HttpMethod.Delete,
            "collections/{collectionId}/folders/{folderId}/comments/{commentId}"
        )
            .SetPathParameter("collectionId", collectionId)
            .SetPathParameter("folderId", folderId)
            .SetPathParameter("commentId", commentId)
            .Build();

        var response = await _httpClient
            .SendAsync(request, cancellationToken)
            .ConfigureAwait(false);

        response.EnsureSuccessfulResponse();
    }
}
