// This file was generated by liblab | https://liblab.com/

using System.Net.Http.Json;
using PostmanClient.Http;
using PostmanClient.Http.Exceptions;
using PostmanClient.Http.Extensions;
using PostmanClient.Http.Serialization;
using PostmanClient.Models;
using PostmanClient.OneOf;

namespace PostmanClient.Services;

public class ImportService : BaseService
{
    internal ImportService(HttpClient httpClient)
        : base(httpClient) { }

    /// <summary>Imports an OpenAPI definition into Postman as a new [Postman Collection](https://learning.postman.com/docs/getting-started/creating-the-first-collection/).</summary>
    /// <param name="workspace">The workspace's ID.</param>
    public async Task<ImportOpenApiDefinitionOkResponse> ImportOpenApiDefinitionAsync(
        JsonSchema input,
        string? workspace = null,
        CancellationToken cancellationToken = default
    )
    {
        ArgumentNullException.ThrowIfNull(input, nameof(input));

        var request = new RequestBuilder(HttpMethod.Post, "import/openapi")
            .SetOptionalQueryParameter("workspace", workspace)
            .SetContentAsJson(input, _jsonSerializerOptions)
            .Build();

        var response = await _httpClient
            .SendAsync(request, cancellationToken)
            .ConfigureAwait(false);

        return await response
                .EnsureSuccessfulResponse()
                .Content.ReadFromJsonAsync<ImportOpenApiDefinitionOkResponse>(
                    _jsonSerializerOptions,
                    cancellationToken
                )
                .ConfigureAwait(false) ?? throw new Exception("Failed to deserialize response.");
    }

    /// <summary>Imports an OpenAPI definition into Postman as a new [Postman Collection](https://learning.postman.com/docs/getting-started/creating-the-first-collection/).</summary>
    /// <param name="workspace">The workspace's ID.</param>
    public async Task<ImportOpenApiDefinitionOkResponse> ImportOpenApiDefinitionAsync(
        JsonStringified input,
        string? workspace = null,
        CancellationToken cancellationToken = default
    )
    {
        ArgumentNullException.ThrowIfNull(input, nameof(input));

        var request = new RequestBuilder(HttpMethod.Post, "import/openapi")
            .SetOptionalQueryParameter("workspace", workspace)
            .SetContentAsJson(input, _jsonSerializerOptions)
            .Build();

        var response = await _httpClient
            .SendAsync(request, cancellationToken)
            .ConfigureAwait(false);

        return await response
                .EnsureSuccessfulResponse()
                .Content.ReadFromJsonAsync<ImportOpenApiDefinitionOkResponse>(
                    _jsonSerializerOptions,
                    cancellationToken
                )
                .ConfigureAwait(false) ?? throw new Exception("Failed to deserialize response.");
    }
}
