// This file was generated by liblab | https://liblab.com/

namespace PostmanClient.Config;

public record ApiKeyAuthConfig(
    string ApiKey,
    string? ApiKeyHeader = ApiKeyAuthConfig.DefaultApiKeyHeader
)
{
    public const string DefaultApiKeyHeader = "X-Api-Key";
}
