// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;
using PostmanClient.Json;

namespace PostmanClient.Models;

public record Accept : ValueEnum<string>
{
    internal Accept(string value)
        : base(value) { }

    public Accept()
        : base("application/vnd.api.v10+json") { }

    public static Accept ApplicationVndApiV10Json = new("application/vnd.api.v10+json");
}
