// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;
using PostmanClient.Json;

namespace PostmanClient.Models;

public record AddApiCollection3(
    /// <value>Information about the collection's contents, such as requests and responses. For a complete list of values, refer to the [collection.json schema file](https://schema.postman.com/json/collection/v2.1.0/collection.json).</value>
    [property:
        JsonPropertyName("data"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        AddApiCollection3.AddApiCollection3Data? Data = null,
    /// <value>The `CREATE_NEW` method.</value>
    [property:
        JsonPropertyName("operationType"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        AddApiCollection3.AddApiCollection3OperationType? OperationType = null
)
{
    /// <summary>Information about the collection's contents, such as requests and responses. For a complete list of values, refer to the [collection.json schema file](https://schema.postman.com/json/collection/v2.1.0/collection.json).</summary>
    public record AddApiCollection3Data(
        /// <value>Information about the collection.</value>
        [property:
            JsonPropertyName("info"),
            JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
        ]
            AddApiCollection3Data.DataInfo? Info = null,
        /// <value>Information about the requests and responses in the collection. For a complete list of values, refer to the [collection.json schema file](https://schema.postman.com/json/collection/v2.1.0/collection.json).</value>
        [property:
            JsonPropertyName("item"),
            JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
        ]
            List<object>? Item = null
    )
    {
        /// <summary>Information about the collection.</summary>
        public record DataInfo(
            /// <value>The collection's name.</value>
            [property:
                JsonPropertyName("name"),
                JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
            ]
                string? Name = null,
            /// <value>The collection's schema format.</value>
            [property:
                JsonPropertyName("schema"),
                JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
            ]
                DataInfo.InfoSchema? Schema = null
        )
        {
            /// <summary>The collection's schema format.</summary>
            public record InfoSchema : ValueEnum<string>
            {
                internal InfoSchema(string value)
                    : base(value) { }

                public InfoSchema()
                    : base("https://schema.getpostman.com/json/collection/v2.1.0/collection.json")
                { }

                public static InfoSchema HttpsSchemaGetpostmanComJsonCollectionV2_1_0CollectionJson =
                    new("https://schema.getpostman.com/json/collection/v2.1.0/collection.json");
            }
        }
    }

    /// <summary>The `CREATE_NEW` method.</summary>
    public record AddApiCollection3OperationType : ValueEnum<string>
    {
        internal AddApiCollection3OperationType(string value)
            : base(value) { }

        public AddApiCollection3OperationType()
            : base("CREATE_NEW") { }

        public static AddApiCollection3OperationType CreateNew = new("CREATE_NEW");
    }
}
