// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;
using PostmanClient.Json;

namespace PostmanClient.Models;

public record AscDesc : ValueEnum<string>
{
    internal AscDesc(string value)
        : base(value) { }

    public AscDesc()
        : base("asc") { }

    public static AscDesc Asc = new("asc");
    public static AscDesc Desc = new("desc");
}
