// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;
using PostmanClient.Json;

namespace PostmanClient.Models;

public record CreateWorkspaceRequest(
    /// <value>Information about the workspace.</value>
    [property:
        JsonPropertyName("workspace"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        CreateWorkspaceRequest.CreateWorkspaceWorkspace1? Workspace = null
)
{
    /// <summary>Information about the workspace.</summary>
    public record CreateWorkspaceWorkspace1(
        /// <value>The workspace's name.</value>
        [property: JsonPropertyName("name")]
            string Name,
        /// <value>
        /// The type of workspace:
        /// - `personal`
        /// - `private` — Private workspaces are available on Postman [**Professional** and **Enterprise** plans](https://www.postman.com/pricing).
        /// - `public`
        /// - `team`
        /// - `partner` — [Partner Workspaces](https://learning.postman.com/docs/collaborating-in-postman/using-workspaces/partner-workspaces/) are available on Postman [**Professional** and **Enterprise** plans](https://www.postman.com/pricing)).
        /// </value>
        [property: JsonPropertyName("type")]
            CreateWorkspaceWorkspace1.WorkspaceType1 Type_,
        /// <value>The workspace's description.</value>
        [property:
            JsonPropertyName("description"),
            JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
        ]
            string? Description = null
    )
    {
        /// <summary>
        /// The type of workspace:
        /// - `personal`
        /// - `private` — Private workspaces are available on Postman [**Professional** and **Enterprise** plans](https://www.postman.com/pricing).
        /// - `public`
        /// - `team`
        /// - `partner` — [Partner Workspaces](https://learning.postman.com/docs/collaborating-in-postman/using-workspaces/partner-workspaces/) are available on Postman [**Professional** and **Enterprise** plans](https://www.postman.com/pricing)).
        /// </summary>
        public record WorkspaceType1 : ValueEnum<string>
        {
            internal WorkspaceType1(string value)
                : base(value) { }

            public WorkspaceType1()
                : base("personal") { }

            public static WorkspaceType1 Personal = new("personal");
            public static WorkspaceType1 Private_ = new("private");
            public static WorkspaceType1 Public_ = new("public");
            public static WorkspaceType1 Team = new("team");
            public static WorkspaceType1 Partner = new("partner");
        }
    }
}
