// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace PostmanClient.Models;

public record CreateWebhookRequest(
    [property:
        JsonPropertyName("webhook"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        CreateWebhookRequest.CreateWebhookWebhook1? Webhook = null
)
{
    public record CreateWebhookWebhook1(
        /// <value>The unique ID of the collection to trigger when calling this webhook.</value>
        [property:
            JsonPropertyName("collection"),
            JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
        ]
            string? Collection = null,
        /// <value>The webhook's name. On success, the system creates a new monitor with this name in the **Monitors** tab.</value>
        [property:
            JsonPropertyName("name"),
            JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
        ]
            string? Name = null
    );
}
