// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace PostmanClient.Models;

public record CreateWorkspaceOkResponse(
    /// <value>Information about the created workspace.</value>
    [property:
        JsonPropertyName("workspace"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        CreateWorkspaceOkResponse.CreateWorkspaceWorkspace2? Workspace = null
)
{
    /// <summary>Information about the created workspace.</summary>
    public record CreateWorkspaceWorkspace2(
        /// <value>The workspace's ID.</value>
        [property:
            JsonPropertyName("id"),
            JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
        ]
            string? Id = null,
        /// <value>The workspace's name.</value>
        [property:
            JsonPropertyName("name"),
            JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
        ]
            string? Name = null
    );
}
