// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace PostmanClient.Models;

public record CreateCollectionForkRequest(
    /// <value>The fork's label.</value>
    [property: JsonPropertyName("label")]
        string Label
);
