// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace PostmanClient.Models;

public record DeletePanElementOrFolder(
    /// <value>The Private API Network element type. The name of the object is the element `api`, `collection`, `workspace`, or `folder` type.</value>
    [property:
        JsonPropertyName("elementType"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        DeletePanElementOrFolder.DeletePanElementOrFolderElementType? ElementType = null
)
{
    /// <summary>The Private API Network element type. The name of the object is the element `api`, `collection`, `workspace`, or `folder` type.</summary>
    public record DeletePanElementOrFolderElementType(
        /// <value>The element's ID.</value>
        [property:
            JsonPropertyName("id"),
            JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
        ]
            string? Id = null
    );
}
