// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace PostmanClient.Models;

/// <summary>Information about the error that occurred during the task's processing.</summary>
public record Details2(
    [property:
        JsonPropertyName("error"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        Details2.Error? Error_ = null
)
{
    public record Error(
        /// <value>The task's error message.</value>
        [property:
            JsonPropertyName("message"),
            JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
        ]
            string? Message = null
    );
}
