// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace PostmanClient.Models;

public record ForkEnvironmentOkResponse(
    /// <value>Information about the forked environment.</value>
    [property:
        JsonPropertyName("environment"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        ForkEnvironmentOkResponse.ForkEnvironmentEnvironment? Environment_ = null
)
{
    /// <summary>Information about the forked environment.</summary>
    public record ForkEnvironmentEnvironment(
        /// <value>The forked environment's ID.</value>
        [property:
            JsonPropertyName("uid"),
            JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
        ]
            string? Uid = null,
        /// <value>The name of the forked environment.</value>
        [property:
            JsonPropertyName("name"),
            JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
        ]
            string? Name = null,
        /// <value>The forked environment's label.</value>
        [property:
            JsonPropertyName("forkName"),
            JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
        ]
            string? ForkName = null
    );
}
