// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace PostmanClient.Models;

public record ForkEnvironmentRequest(
    /// <value>The forked environment's label.</value>
    [property: JsonPropertyName("forkName")]
        string ForkName
);
