// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;
using PostmanClient.Json;

namespace PostmanClient.Models;

public record Format : ValueEnum<string>
{
    internal Format(string value)
        : base(value) { }

    public Format()
        : base("json") { }

    public static Format Json = new("json");
    public static Format Yaml = new("yaml");
}
