// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;
using PostmanClient.Json;

namespace PostmanClient.Models;

public record GetAllPanAddElementRequestsStatus : ValueEnum<string>
{
    internal GetAllPanAddElementRequestsStatus(string value)
        : base(value) { }

    public GetAllPanAddElementRequestsStatus()
        : base("pending") { }

    public static GetAllPanAddElementRequestsStatus Pending = new("pending");
    public static GetAllPanAddElementRequestsStatus Denied = new("denied");
}
