// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;
using PostmanClient.Json;

namespace PostmanClient.Models;

public record GetAllElementsAndFoldersSort : ValueEnum<string>
{
    internal GetAllElementsAndFoldersSort(string value)
        : base(value) { }

    public GetAllElementsAndFoldersSort()
        : base("createdAt") { }

    public static GetAllElementsAndFoldersSort CreatedAt = new("createdAt");
    public static GetAllElementsAndFoldersSort UpdatedAt = new("updatedAt");
}
