// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace PostmanClient.Models;

public record GetAccountInvoices([property: JsonPropertyName("data")] List<InvoiceData> Data);
