// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;
using PostmanClient.Json;

namespace PostmanClient.Models;

public record GetEnvironmentForksSort : ValueEnum<string>
{
    internal GetEnvironmentForksSort(string value)
        : base(value) { }

    public GetEnvironmentForksSort()
        : base("createdAt") { }

    public static GetEnvironmentForksSort CreatedAt = new("createdAt");
}
