// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace PostmanClient.Models;

public record GetSourceCollectionStatus(
    [property:
        JsonPropertyName("collection"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        GetSourceCollectionStatus.GetSourceCollectionStatusCollection? Collection = null
)
{
    public record GetSourceCollectionStatusCollection(
        /// <value>Information about the forked collection. The object's name is the forked collection's UID (`userId`-`collectionId`).</value>
        [property:
            JsonPropertyName("collectionUid"),
            JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
        ]
            GetSourceCollectionStatusCollection.CollectionUid? CollectionUid_ = null
    )
    {
        /// <summary>Information about the forked collection. The object's name is the forked collection's UID (`userId`-`collectionId`).</summary>
        public record CollectionUid(
            /// <value>If true, there is a difference between the forked collection and its source collection.</value>
            [property:
                JsonPropertyName("isSourceAhead"),
                JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
            ]
                bool? IsSourceAhead = null
        );
    }
}
