// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;
using PostmanClient.Json;

namespace PostmanClient.Models;

public record GetTaggedEntitiesEntityType : ValueEnum<string>
{
    internal GetTaggedEntitiesEntityType(string value)
        : base(value) { }

    public GetTaggedEntitiesEntityType()
        : base("api") { }

    public static GetTaggedEntitiesEntityType Api = new("api");
    public static GetTaggedEntitiesEntityType Collection = new("collection");
    public static GetTaggedEntitiesEntityType Workspace = new("workspace");
}
