// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;
using PostmanClient.Json;

namespace PostmanClient.Models;

public record GetWorkspacesType : ValueEnum<string>
{
    internal GetWorkspacesType(string value)
        : base(value) { }

    public GetWorkspacesType()
        : base("personal") { }

    public static GetWorkspacesType Personal = new("personal");
    public static GetWorkspacesType Team = new("team");
    public static GetWorkspacesType Private_ = new("private");
    public static GetWorkspacesType Public_ = new("public");
    public static GetWorkspacesType Partner = new("partner");
}
