// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;
using PostmanClient.Json;

namespace PostmanClient.Models;

/// <summary>Information about the global variable.</summary>
public record GlobalVariable(
    /// <value>The variable's name.</value>
    [property:
        JsonPropertyName("key"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? Key = null,
    /// <value>The [type](https://learning.postman.com/docs/sending-requests/variables/#variable-types) of variable.</value>
    [property:
        JsonPropertyName("type"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        GlobalVariable.GlobalVariableType? Type_ = null,
    /// <value>The variable's value.</value>
    [property:
        JsonPropertyName("value"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? Value = null,
    /// <value>If true, the variable is enabled.</value>
    [property:
        JsonPropertyName("enabled"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        bool? Enabled = null
)
{
    /// <summary>The [type](https://learning.postman.com/docs/sending-requests/variables/#variable-types) of variable.</summary>
    public record GlobalVariableType : ValueEnum<string>
    {
        internal GlobalVariableType(string value)
            : base(value) { }

        public GlobalVariableType()
            : base("default") { }

        public static GlobalVariableType Default_ = new("default");
        public static GlobalVariableType Secret = new("secret");
    }
}
