// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;
using PostmanClient.Json;

namespace PostmanClient.Models;

public record ImportExportFile(
    /// <value>The `file` type value.</value>
    [property: JsonPropertyName("type")]
        ImportExportFile.ImportExportFileType Type_,
    /// <value>A file containing a valid user's export .zip file.</value>
    [property: JsonPropertyName("input")]
        object Input_
)
{
    /// <summary>The `file` type value.</summary>
    public record ImportExportFileType : ValueEnum<string>
    {
        internal ImportExportFileType(string value)
            : base(value) { }

        public ImportExportFileType()
            : base("file") { }

        public static ImportExportFileType File = new("file");
    }
}
