// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace PostmanClient.Models;

public record PanCreateApi(
    [property: JsonPropertyName("api"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        PanCreateApi.PanCreateApiApi? Api = null
)
{
    public record PanCreateApiApi(
        /// <value>The API's ID.</value>
        [property: JsonPropertyName("id")]
            string Id,
        /// <value>The API's parent folder ID.</value>
        [property: JsonPropertyName("parentFolderId")]
            long ParentFolderId
    );
}
