// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace PostmanClient.Models;

public record PanCreateFolder(
    [property:
        JsonPropertyName("folder"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        PanCreateFolder.PanCreateFolderFolder? Folder = null
)
{
    public record PanCreateFolderFolder(
        /// <value>The folder's name.</value>
        [property: JsonPropertyName("name")]
            string Name,
        /// <value>The folder's description.</value>
        [property:
            JsonPropertyName("description"),
            JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
        ]
            string? Description = null,
        /// <value>The folder's parent folder ID. This value defaults to `0`. To create a folder at the root level, omit this property.</value>
        [property:
            JsonPropertyName("parentFolderId"),
            JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
        ]
            long? ParentFolderId = null
    );
}
