// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace PostmanClient.Models;

public record PanCreateCollection(
    [property:
        JsonPropertyName("collection"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        PanCreateCollection.PanCreateCollectionCollection? Collection = null
)
{
    public record PanCreateCollectionCollection(
        /// <value>The collection's ID.</value>
        [property: JsonPropertyName("id")]
            string Id,
        /// <value>The collection's parent folder ID.</value>
        [property: JsonPropertyName("parentFolderId")]
            long ParentFolderId,
        /// <value>A list of environment UIDs (`userId`-`environmentId``) to add to the collection.</value>
        [property:
            JsonPropertyName("environments"),
            JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
        ]
            List<string>? Environments = null
    );
}
