// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace PostmanClient.Models;

public record PatchCollectionOkResponse(
    [property:
        JsonPropertyName("collection"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        PatchCollectionOkResponse.PatchCollectionCollection2? Collection = null
)
{
    public record PatchCollectionCollection2(
        /// <value>The collection's ID.</value>
        [property:
            JsonPropertyName("id"),
            JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
        ]
            string? Id = null,
        /// <value>The collection's updated name.</value>
        [property:
            JsonPropertyName("name"),
            JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
        ]
            string? Name = null,
        /// <value>The collection's updated description.</value>
        [property:
            JsonPropertyName("description"),
            JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
        ]
            string? Description = null
    );
}
