// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace PostmanClient.Models;

public record PublishMock(
    [property:
        JsonPropertyName("mock"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        PublishMock.PublishMockMock? Mock = null
)
{
    public record PublishMockMock(
        /// <value>The mock server's ID.</value>
        [property:
            JsonPropertyName("id"),
            JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
        ]
            string? Id = null
    );
}
