// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;
using PostmanClient.Json;

namespace PostmanClient.Models;

public record PullRequestUpdated(
    /// <value>The date and time at which the pull request was created.</value>
    [property:
        JsonPropertyName("createdAt"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? CreatedAt = null,
    /// <value>The ID of the user who created the pull request.</value>
    [property:
        JsonPropertyName("createdBy"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? CreatedBy = null,
    /// <value>The pull request's description.</value>
    [property:
        JsonPropertyName("description"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? Description = null,
    /// <value>The pull request's merge destination ID.</value>
    [property:
        JsonPropertyName("destinationId"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? DestinationId = null,
    /// <value>The type of forked element.</value>
    [property:
        JsonPropertyName("forkType"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? ForkType = null,
    /// <value>The pull request's ID.</value>
    [property: JsonPropertyName("id"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        string? Id = null,
    /// <value>The unique ID of the source element.</value>
    [property:
        JsonPropertyName("sourceId"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? SourceId = null,
    /// <value>The pull request's status.</value>
    [property:
        JsonPropertyName("status"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        PullRequestUpdated.PullRequestUpdatedStatus? Status = null,
    /// <value>The pull request's title.</value>
    [property:
        JsonPropertyName("title"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? Title = null,
    /// <value>The date and time at which the pull request was updated.</value>
    [property:
        JsonPropertyName("updatedAt"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? UpdatedAt = null
)
{
    /// <summary>The pull request's status.</summary>
    public record PullRequestUpdatedStatus : ValueEnum<string>
    {
        internal PullRequestUpdatedStatus(string value)
            : base(value) { }

        public PullRequestUpdatedStatus()
            : base("open") { }

        public static PullRequestUpdatedStatus Open = new("open");
        public static PullRequestUpdatedStatus Approved = new("approved");
        public static PullRequestUpdatedStatus Declined = new("declined");
        public static PullRequestUpdatedStatus Merged = new("merged");
    }
}
