// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace PostmanClient.Models;

public record PullRequestUpdate(
    /// <value>The pull request's updated title.</value>
    [property: JsonPropertyName("title")]
        string Title,
    /// <value>An updated list of the pull request's assigned reviewers. This replaces all existing users assigned to the pull request with those you pass in the request body.</value>
    [property: JsonPropertyName("reviewers")]
        List<string> Reviewers,
    /// <value>The updated pull request description.</value>
    [property:
        JsonPropertyName("description"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? Description = null
);
