// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace PostmanClient.Models;

public record PullEnvironmentRequest(
    /// <value>The source environment's unique ID to pull data from.</value>
    [property:
        JsonPropertyName("source"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? Source = null
);
