// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace PostmanClient.Models;

public record TagGetPut(
    /// <value>A list of associated tags.</value>
    [property:
        JsonPropertyName("tags"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        List<TagGetPut.TagGetPutTags>? Tags = null
)
{
    /// <summary>Information about the tag.</summary>
    public record TagGetPutTags(
        /// <value>The tag's ID within a team or individual (non-team) user scope.</value>
        [property:
            JsonPropertyName("slug"),
            JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
        ]
            string? Slug = null
    );
}
