// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace PostmanClient.Models;

public record TransferCollectionItems200Error(
    /// <value>A list of the transferred collection request, response, or folder UIDs.</value>
    [property:
        JsonPropertyName("ids"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        List<string>? Ids = null
);
