// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;
using PostmanClient.Json;

namespace PostmanClient.Models;

public record UpdateCollectionRoles(
    [property: JsonPropertyName("roles")]
        List<UpdateCollectionRoles.UpdateCollectionRolesRoles> Roles
)
{
    public record UpdateCollectionRolesRoles(
        /// <value>The operation to perform on the path.</value>
        [property: JsonPropertyName("op")]
            UpdateCollectionRolesRoles.RolesOp Op,
        /// <value>The resource to perform the action on.</value>
        [property: JsonPropertyName("path")]
            UpdateCollectionRolesRoles.RolesPath1 Path,
        [property: JsonPropertyName("value")] List<UpdateCollectionRolesRoles.RolesValue1> Value
    )
    {
        /// <summary>The operation to perform on the path.</summary>
        public record RolesOp : ValueEnum<string>
        {
            internal RolesOp(string value)
                : base(value) { }

            public RolesOp()
                : base("update") { }

            public static RolesOp Update = new("update");
        }

        /// <summary>The resource to perform the action on.</summary>
        public record RolesPath1 : ValueEnum<string>
        {
            internal RolesPath1(string value)
                : base(value) { }

            public RolesPath1()
                : base("/user") { }

            public static RolesPath1 User = new("/user");
            public static RolesPath1 Group = new("/group");
            public static RolesPath1 Team = new("/team");
        }

        /// <summary>Information about the updated role.</summary>
        public record RolesValue1(
            /// <value>The user, group, or team's ID.</value>
            [property: JsonPropertyName("id")]
                double Id,
            /// <value>
            /// The role type:
            /// - `VIEWER` — Can view, fork, and export collections.
            /// - `EDITOR` — Can edit collections directly.
            /// </value>
            [property: JsonPropertyName("role")]
                RolesValue1.ValueRole1 Role
        )
        {
            /// <summary>
            /// The role type:
            /// - `VIEWER` — Can view, fork, and export collections.
            /// - `EDITOR` — Can edit collections directly.
            /// </summary>
            public record ValueRole1 : ValueEnum<string>
            {
                internal ValueRole1(string value)
                    : base(value) { }

                public ValueRole1()
                    : base("VIEWER") { }

                public static ValueRole1 Viewer = new("VIEWER");
                public static ValueRole1 Editor = new("EDITOR");
            }
        }
    }
}
