// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace PostmanClient.Models;

public record UpdateCollectionFolder(
    /// <value>The folder's updated information, including the updated properties. For a complete list of properties, refer to the [collection.json schema file](https://schema.postman.com/collection/json/v1.0.0/draft-07/collection.json).</value>
    [property:
        JsonPropertyName("data"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        object? Data = null,
    /// <value>A Postman-specific response that contains information about the internal performed operation.</value>
    [property:
        JsonPropertyName("meta"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        object? Meta = null,
    /// <value>The folder's ID.</value>
    [property:
        JsonPropertyName("model_id"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? ModelId = null,
    /// <value>An internal revision ID. Its value increments each time the resource changes. You can use this ID to track whether there were changes since the last time you fetched the resource.</value>
    [property:
        JsonPropertyName("revision"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        double? Revision = null
);
