// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace PostmanClient.Models;

public record UpdateWorkspaceOkResponse(
    /// <value>Information about the updated workspace.</value>
    [property:
        JsonPropertyName("workspace"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        UpdateWorkspaceOkResponse.UpdateWorkspaceWorkspace2? Workspace = null
)
{
    /// <summary>Information about the updated workspace.</summary>
    public record UpdateWorkspaceWorkspace2(
        /// <value>The workspace's ID.</value>
        [property:
            JsonPropertyName("id"),
            JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
        ]
            string? Id = null,
        /// <value>The workspace's name.</value>
        [property:
            JsonPropertyName("name"),
            JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
        ]
            string? Name = null
    );
}
