// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;
using PostmanClient.Json;

namespace PostmanClient.Models;

public record UpdateWorkspaceRequest(
    [property:
        JsonPropertyName("workspace"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        UpdateWorkspaceRequest.UpdateWorkspaceWorkspace1? Workspace = null
)
{
    public record UpdateWorkspaceWorkspace1(
        /// <value>The workspace's new name.</value>
        [property:
            JsonPropertyName("name"),
            JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
        ]
            string? Name = null,
        /// <value>
        /// The new workspace visibility [type](https://learning.postman.com/docs/collaborating-in-postman/using-workspaces/managing-workspaces/#changing-workspace-visibility). This property does not support the following workspace visibility changes:
        /// - `private` to `public`, `public` to `private`, and `private` to `personal` for Free and Basic [plans](https://www.postman.com/pricing/).
        /// - `public` to `personal` for team users.
        /// </value>
        [property:
            JsonPropertyName("type"),
            JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
        ]
            UpdateWorkspaceWorkspace1.WorkspaceType3? Type_ = null,
        /// <value>The new workspace description.</value>
        [property:
            JsonPropertyName("description"),
            JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
        ]
            string? Description = null
    )
    {
        /// <summary>
        /// The new workspace visibility [type](https://learning.postman.com/docs/collaborating-in-postman/using-workspaces/managing-workspaces/#changing-workspace-visibility). This property does not support the following workspace visibility changes:
        /// - `private` to `public`, `public` to `private`, and `private` to `personal` for Free and Basic [plans](https://www.postman.com/pricing/).
        /// - `public` to `personal` for team users.
        /// </summary>
        public record WorkspaceType3 : ValueEnum<string>
        {
            internal WorkspaceType3(string value)
                : base(value) { }

            public WorkspaceType3()
                : base("private") { }

            public static WorkspaceType3 Private_ = new("private");
            public static WorkspaceType3 Personal = new("personal");
            public static WorkspaceType3 Team = new("team");
            public static WorkspaceType3 Public_ = new("public");
        }
    }
}
