// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;
using PostmanClient.Json;

namespace PostmanClient.Models;

public record UpdateEnvironmentRequest(
    [property:
        JsonPropertyName("environment"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        UpdateEnvironmentRequest.UpdateEnvironmentEnvironment1? Environment_ = null
)
{
    public record UpdateEnvironmentEnvironment1(
        /// <value>The environment's name.</value>
        [property:
            JsonPropertyName("name"),
            JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
        ]
            string? Name = null,
        /// <value>Information about the environment's variables.</value>
        [property:
            JsonPropertyName("values"),
            JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
        ]
            List<UpdateEnvironmentEnvironment1.EnvironmentValues3>? Values = null
    )
    {
        public record EnvironmentValues3(
            /// <value>If true, the variable is enabled.</value>
            [property:
                JsonPropertyName("enabled"),
                JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
            ]
                bool? Enabled = null,
            /// <value>The variable's name.</value>
            [property:
                JsonPropertyName("key"),
                JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
            ]
                string? Key = null,
            /// <value>The variable's value.</value>
            [property:
                JsonPropertyName("value"),
                JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
            ]
                string? Value = null,
            /// <value>The variable type.</value>
            [property:
                JsonPropertyName("type"),
                JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
            ]
                EnvironmentValues3.ValuesType3? Type_ = null
        )
        {
            /// <summary>The variable type.</summary>
            public record ValuesType3 : ValueEnum<string>
            {
                internal ValuesType3(string value)
                    : base(value) { }

                public ValuesType3()
                    : base("secret") { }

                public static ValuesType3 Secret = new("secret");
                public static ValuesType3 Default_ = new("default");
                public static ValuesType3 Any = new("any");
            }
        }
    }
}
