// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace PostmanClient.Models;

public record UpdatePanFolder(
    [property:
        JsonPropertyName("folder"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        UpdatePanFolder.UpdatePanFolderFolder? Folder = null
)
{
    public record UpdatePanFolderFolder(
        /// <value>The folder's new name.</value>
        [property:
            JsonPropertyName("name"),
            JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
        ]
            string? Name = null,
        /// <value>The folder's updated description.</value>
        [property:
            JsonPropertyName("description"),
            JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
        ]
            string? Description = null,
        /// <value>The folder's new parent folder ID.</value>
        [property:
            JsonPropertyName("parentFolderId"),
            JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
        ]
            long? ParentFolderId = null
    );
}
