// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;
using PostmanClient.Json;

namespace PostmanClient.Models;

public record UpdateDetectedSecretResolutionsRequest(
    /// <value>
    /// The secret's updated resolution status:
    /// - `FALSE_POSITIVE` — The discovered secret is not an actual secret.
    /// - `REVOKED` — The secret is valid, but the user rotated their key to resolve the issue.
    /// - `ACCEPTED_RISK` — The Secret Scanner found the secret, but user accepts the risk of publishing it.
    /// </value>
    [property: JsonPropertyName("resolution")]
        UpdateDetectedSecretResolutionsRequest.UpdateSecretResolutionsResolution1 Resolution,
    /// <value>The ID of the workspace that contains the secret.</value>
    [property: JsonPropertyName("workspaceId")]
        string WorkspaceId
)
{
    /// <summary>
    /// The secret's updated resolution status:
    /// - `FALSE_POSITIVE` — The discovered secret is not an actual secret.
    /// - `REVOKED` — The secret is valid, but the user rotated their key to resolve the issue.
    /// - `ACCEPTED_RISK` — The Secret Scanner found the secret, but user accepts the risk of publishing it.
    /// </summary>
    public record UpdateSecretResolutionsResolution1 : ValueEnum<string>
    {
        internal UpdateSecretResolutionsResolution1(string value)
            : base(value) { }

        public UpdateSecretResolutionsResolution1()
            : base("FALSE_POSITIVE") { }

        public static UpdateSecretResolutionsResolution1 FalsePositive = new("FALSE_POSITIVE");
        public static UpdateSecretResolutionsResolution1 Revoked = new("REVOKED");
        public static UpdateSecretResolutionsResolution1 AcceptedRisk = new("ACCEPTED_RISK");
    }
}
