// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;
using PostmanClient.Json;

namespace PostmanClient.Models;

public record UpdateMockServerResponse(
    [property:
        JsonPropertyName("serverResponse"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        UpdateMockServerResponse.UpdateMockServerResponseServerResponse? ServerResponse = null
)
{
    public record UpdateMockServerResponseServerResponse(
        /// <value>The server response's name.</value>
        [property:
            JsonPropertyName("name"),
            JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
        ]
            string? Name = null,
        /// <value>The server response's 5xx HTTP response code. This property only accepts 5xx values.</value>
        [property:
            JsonPropertyName("statusCode"),
            JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
        ]
            long? StatusCode = null,
        /// <value>The server response's request headers, such as Content-Type, Accept, encoding, and other information.</value>
        [property:
            JsonPropertyName("headers"),
            JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
        ]
            List<UpdateMockServerResponseServerResponse.ServerResponseHeaders2>? Headers = null,
        /// <value>The server response's body language type.</value>
        [property: JsonPropertyName("language")]
            UpdateMockServerResponseServerResponse.ServerResponseLanguage2? Language = null,
        /// <value>The server response's body that returns when calling the mock server.</value>
        [property:
            JsonPropertyName("body"),
            JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
        ]
            string? Body = null
    )
    {
        /// <summary>Information about they key-value pair.</summary>
        public record ServerResponseHeaders2(
            /// <value>The request header's key value.</value>
            [property:
                JsonPropertyName("key"),
                JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
            ]
                string? Key = null,
            /// <value>The request header's value.</value>
            [property:
                JsonPropertyName("value"),
                JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
            ]
                string? Value = null
        );

        /// <summary>The server response's body language type.</summary>
        public record ServerResponseLanguage2 : ValueEnum<string>
        {
            internal ServerResponseLanguage2(string value)
                : base(value) { }

            public ServerResponseLanguage2()
                : base("text") { }

            public static ServerResponseLanguage2 Text = new("text");
            public static ServerResponseLanguage2 Javascript = new("javascript");
            public static ServerResponseLanguage2 Json = new("json");
            public static ServerResponseLanguage2 Html = new("html");
            public static ServerResponseLanguage2 Xml = new("xml");
        }
    }
}
