// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace PostmanClient.Models;

public record UpdatePanApi(
    [property: JsonPropertyName("api"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        UpdatePanApi.UpdatePanApiApi? Api = null
)
{
    public record UpdatePanApiApi(
        /// <value>The API's new parent folder ID.</value>
        [property:
            JsonPropertyName("parentFolderId"),
            JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
        ]
            long? ParentFolderId = null
    );
}
