// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace PostmanClient.Models;

/// <summary>Information about the API version.</summary>
public record UpdateApiVersionRequest(
    /// <value>The version's name.</value>
    [property: JsonPropertyName("name")]
        string Name,
    /// <value>The version's Markdown-supported release notes.</value>
    [property:
        JsonPropertyName("releaseNotes"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? ReleaseNotes = null
);
