// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;
using PostmanClient.Json;

namespace PostmanClient.Models;

public record UpdateWorkspaceRolesOkResponse(
    [property:
        JsonPropertyName("roles"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        List<UpdateWorkspaceRolesOkResponse.UpdateWorkspaceRolesRoles2>? Roles = null
)
{
    public record UpdateWorkspaceRolesRoles2(
        /// <value>The role's ID.</value>
        [property:
            JsonPropertyName("id"),
            JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
        ]
            long? Id = null,
        /// <value>A list of user IDs assigned to the role.</value>
        [property:
            JsonPropertyName("user"),
            JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
        ]
            List<double>? User = null,
        /// <value>A list of user group IDs assigned to the role.</value>
        [property:
            JsonPropertyName("usergroup"),
            JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
        ]
            List<double>? Usergroup = null,
        /// <value>The role's display name.</value>
        [property:
            JsonPropertyName("displayName"),
            JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
        ]
            UpdateWorkspaceRolesRoles2.DisplayName? DisplayName_ = null
    )
    {
        /// <summary>The role's display name.</summary>
        public record DisplayName : ValueEnum<string>
        {
            internal DisplayName(string value)
                : base(value) { }

            public DisplayName()
                : base("Admin") { }

            public static DisplayName Admin = new("Admin");
            public static DisplayName Viewer = new("Viewer");
            public static DisplayName Editor = new("Editor");
        }
    }
}
