// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;
using PostmanClient.Json;

namespace PostmanClient.Models;

public record UpdateWorkspaceRolesRequest(
    [property:
        JsonPropertyName("roles"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        List<UpdateWorkspaceRolesRequest.UpdateWorkspaceRolesRoles1>? Roles = null
)
{
    public record UpdateWorkspaceRolesRoles1(
        /// <value>The operation to perform on the path.</value>
        [property: JsonPropertyName("op")]
            string Op,
        /// <value>The resource to perform the action on.</value>
        [property: JsonPropertyName("path")]
            UpdateWorkspaceRolesRoles1.RolesPath2 Path,
        [property: JsonPropertyName("value")] List<UpdateWorkspaceRolesRoles1.RolesValue2> Value
    )
    {
        /// <summary>The resource to perform the action on.</summary>
        public record RolesPath2 : ValueEnum<string>
        {
            internal RolesPath2(string value)
                : base(value) { }

            public RolesPath2()
                : base("/user") { }

            public static RolesPath2 User = new("/user");
            public static RolesPath2 Usergroup = new("/usergroup");
        }

        /// <summary>Information about the updated user or user group role.</summary>
        public record RolesValue2(
            /// <value>The user or user group ID.</value>
            [property: JsonPropertyName("id")]
                string Id,
            /// <value>
            /// The workspace role's ID:
            /// - `1` — Viewer. Can view, fork, and export workspace resources.
            /// - `2` — Editor. Can create and edit workspace resources.
            /// - `3` — Admin. Can manage workspace details and members.
            /// </value>
            [property: JsonPropertyName("role")]
                RolesValue2.ValueRole2 Role
        )
        {
            /// <summary>
            /// The workspace role's ID:
            /// - `1` — Viewer. Can view, fork, and export workspace resources.
            /// - `2` — Editor. Can create and edit workspace resources.
            /// - `3` — Admin. Can manage workspace details and members.
            /// </summary>
            public enum ValueRole2
            {
                _1 = 1,
                _2 = 2,
                _3 = 3
            }
        }
    }
}
